### ISSUE TITLE
recurrent reminder

### ISSUE THREAD

**Issue by leoauri** [glesik/wifireminders#13]
Request: recurrent reminder whenever the hotspot is left and returned to, for example if I leave home and return again, same reminder without having to set it again.
I realise this means somewhat of a redesign, but I'd find it really useful!

**Comment by glesik** [comment]
It's rather tricky to implement if polling mode is enabled (interval > 0). Otherwise I can probably just add "dismiss" button to notification which disables the reminder. If it's not pressed or the notification is swiped away, it would remain enabled.

**Comment by leoauri** [comment]
That'd work perfectly for me...

**Comment by ildar** [comment]
Great idea!

**Comment by glesik** [comment]
Please check out v1.2.4. Dismiss button to disable reminder must be available on Android 4.1 and later. On earlier versions or if polling is enabled reminders will be disabled automatically.
