### ISSUE TITLE
reminder description field has a wrong attribute

### ISSUE THREAD

**Issue by ildar** [glesik/wifireminders#14]
I don't really know which attr is wrong. But when I swipe the text in, spaces aren't inserted between word.
That behavior is usually observed in special-type fields like page address field in browsers.

**Comment by glesik** [comment]
What do you mean by "swiping text in"? The reminder text field has "textCapSentences|textMultiLine" properties which indicate that it should start with capital and allow multiline text, that's all.

**Comment by ildar** [comment]
I mean that Gesture typing in a standard Android keyboard (JB+) should
allow entering words without taping SPACE, like in
https://www.youtube.com/watch?v=JeJYbID_dU4 . WiFi reminders is the
exception in this regard: spaces aren't autoinserted.
>
>   --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by glesik** [comment]
I've just installed latest Google Keyboard and the spaces are inserted automatically during gesture typing. Which keyboard version are you using?

**Comment by ildar** [comment]
Sorry to raise the old and minor issue again.
Just to be sure that we understand each other: the app has two separate
interfaces: for adding a reminder and editing editing.The issue is seen in
the Edit but not in the Add.
Also if you still don't see the issue,maybe version info can help: I've
seen it in KitKat and older. Both Google kbd and AOSP kbd tested.
>
> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by glesik** [comment]
Sorry, I think I got it now. I've added [TYPE_CLASS_TEXT](http://developer.android.com/reference/android/text/InputType.html#TYPE_CLASS_TEXT) and [TYPE_TEXT_FLAG_AUTO_CORRECT](http://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_FLAG_AUTO_CORRECT) flags to text edit fields, please test v1.2.5 (should appear in F-Droid soon).

**Comment by ildar** [comment]
The result is perfect, thank you very much!
