### ISSUE TITLE
WiFi poll interval

### ISSUE THREAD

**Issue by ildar** [glesik/wifireminders#5]
Please clarify its function:
1. Through it I suspect that WiFi reminders polls but it isn't good for battery etc.
2. Isn't it better to check WiFi APs on connect events?

Thanx for the app: the idea was rolling in my mind for a long time already! Now you seem to implement it! Спасибо!

**Comment by glesik** [comment]
Wi-Fi broadcast receiver mode works for me for a while now, so I consider this issue closed.

**Comment by ildar** [comment]
Yeah, thanks a lot!
